server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: multi-tenant-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/multi_tenant_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        multiTenancy: SCHEMA
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: true

  flyway:
    enabled: true
    default-schema: public
    schemas: public
    locations: classpath:db/migration
    validate-on-migrate: false
    out-of-order: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

keycloak:
  jwks-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8081/realms/RegistruAgricol/protocol/openid-connect/certs}
