server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: multi-tenant-backend
  mail:
    host: ${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${SPRING_MAIL_PORT:2525}
    username: ${SPRING_MAIL_USERNAME:cb8c1d1d205848}
    password: ${SPRING_MAIL_PASSWORD:42f4848e772da2}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/multi_tenant_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        multiTenancy: SCHEMA
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: true

  flyway:
    enabled: true
    default-schema: public
    schemas: public
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

app:
  crypto:
    aes-key: ${APP_CRYPTO_AES_KEY:MyDefaultAesSymmetricEncryptionKey2026Registru}
  mail:
    from: ${APP_MAIL_FROM:test@test.ro}
