-- Add deleted column to all tenant tables
ALTER TABLE vita_de_vie ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE terenuri ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE surse_apa ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pomi ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pasuni_fanete ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE parcele ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE utilaje ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE gospodarii ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE documente ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE culturi_parcele ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE contracte_utilizare ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cladiri ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cereri ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE categorii_folosinta ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE carti_funciare ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE person_relations ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE identity_documents ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE persons ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE uats ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE animale_individuale ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE evenimente_animale ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE efective_grup ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;

-- Add deleted column to Envers audit tables
ALTER TABLE gospodarii_aud ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cladiri_aud ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE parcele_aud ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE persons_aud ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE terenuri_aud ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;

-- Update Unique Constraints to Partial Indexes
-- uats.cod_siruta
ALTER TABLE uats DROP CONSTRAINT IF EXISTS uat_cod_siruta_key;
ALTER TABLE uats DROP CONSTRAINT IF EXISTS uats_cod_siruta_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_uats_cod_siruta ON uats(cod_siruta) WHERE deleted = false;

-- cereri.cod_cerere
ALTER TABLE cereri DROP CONSTRAINT IF EXISTS cereri_cod_cerere_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_cereri_cod_cerere ON cereri(cod_cerere) WHERE deleted = false;

-- carti_funciare.teren_id
ALTER TABLE carti_funciare DROP CONSTRAINT IF EXISTS carti_funciare_teren_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_carti_funciare_teren_id ON carti_funciare(teren_id) WHERE deleted = false;
