-- Create Atestate Producator table
CREATE TABLE atestate_producator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numar_atestat VARCHAR(50) NOT NULL UNIQUE,
    seria VARCHAR(10) NOT NULL,
    persoana_id BIGINT NOT NULL,
    data_eliberare DATE NOT NULL,
    valabilitate_luni INT NOT NULL DEFAULT 60,
    observatii TEXT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atestate_persoane FOREIGN KEY (persoana_id) REFERENCES persons(id) ON DELETE CASCADE
);

-- Partial unique index for numar_atestat
ALTER TABLE atestate_producator DROP CONSTRAINT IF EXISTS atestate_producator_numar_atestat_key;
CREATE UNIQUE INDEX idx_atestate_producator_numar_atestat_unique ON atestate_producator (numar_atestat) WHERE deleted = false;

-- Create Carnete Comercializare table
CREATE TABLE carnete_comercializare (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numar_carnet VARCHAR(50) NOT NULL UNIQUE,
    seria VARCHAR(10) NOT NULL,
    atestat_id BIGINT NOT NULL,
    persoana_id BIGINT NOT NULL,
    data_eliberare DATE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carnete_atestate FOREIGN KEY (atestat_id) REFERENCES atestate_producator(id) ON DELETE CASCADE,
    CONSTRAINT fk_carnete_persoane FOREIGN KEY (persoana_id) REFERENCES persons(id) ON DELETE CASCADE
);

-- Partial unique index for numar_carnet
ALTER TABLE carnete_comercializare DROP CONSTRAINT IF EXISTS carnete_comercializare_numar_carnet_key;
CREATE UNIQUE INDEX idx_carnete_comercializare_numar_carnet_unique ON carnete_comercializare (numar_carnet) WHERE deleted = false;

-- Create Envers audit tables
CREATE TABLE atestate_producator_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    numar_atestat VARCHAR(50),
    seria VARCHAR(10),
    persoana_id BIGINT,
    data_eliberare DATE,
    valabilitate_luni INT,
    observatii TEXT,
    deleted BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_atestate_producator_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE carnete_comercializare_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    numar_carnet VARCHAR(50),
    seria VARCHAR(10),
    atestat_id BIGINT,
    persoana_id BIGINT,
    data_eliberare DATE,
    deleted BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_carnete_comercializare_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

-- Modify cereri table
ALTER TABLE cereri ADD COLUMN tip_cerere VARCHAR(50) NOT NULL DEFAULT 'GENERALA';
