package com.multitenant.model.registru;

public enum TipCerere {
    ELIBERARE_ATESTAT_PRODUCATOR,
    ELIBERARE_CARNET_COMERCIALIZARE,
    ADEVERINTA_ROL,
    SESIZARE_AMBROZIA,
    ADEVERINTA_AVIZ_CONSULTATIV,
    ADEVERINTA_TEREN_PF,
    ADEVERINTA_TEREN_PJ,
    COPIE_REGISTRU_1959_1963,
    EXTRAS_REGISTRU_PF,
    EXTRAS_REGISTRU_PJ,
    ADEVERINTA_DETINERE_TEREN
}
